-- vim.opt.whichwrap = false	-- list of flags specifying which commands wrap to another line
-- vim.opt.startofline = false	-- many jump commands move the cursor to the first non-blank
-- vim.opt.paragraphs = false	-- nroff macro names that separate paragraphs
-- vim.opt.sections = false	-- nroff macro names that separate sections
-- vim.opt.path = false	-- list of directory names used for file searching
-- vim.opt.cdhome = false	-- :cd without argument goes to the home directory
-- vim.opt.cdpath = false	-- list of directory names used for :cd
-- vim.opt.autochdir = false	-- change to directory of file in buffer
-- vim.opt.wrapscan = false	-- search commands wrap around the end of the buffer
vim.opt.incsearch = true	-- show match for partly typed search command
-- vim.opt.magic = false	-- change the way backslashes are used in search patterns
-- vim.opt.regexpengine = false	-- select the default regexp engine used
vim.opt.ignorecase = true	-- ignore case when using a search pattern
vim.opt.smartcase = true	-- override 'ignorecase' when pattern has upper case characters
-- vim.opt.casemap = false	-- what method to use for changing case of letters
-- vim.opt.maxmempattern = false	-- maximum amount of memory in Kbyte used for pattern matching
-- vim.opt.define = false	-- pattern for a macro definition line
-- vim.opt.include = false	-- pattern for an include-file line
-- vim.opt.includeexpr = false	-- expression used to transform an include line to a file name
