-- vim.opt.background = false	-- "dark" or "light"; the background color brightness
-- vim.opt.filetype = false	-- type of file; triggers the FileType event when set
-- vim.opt.syntax = false	-- name of syntax highlighting used
-- vim.opt.synmaxcol = false	-- maximum column to look for syntax items
-- vim.opt.highlight = false	-- which highlighting to use for various occasions
vim.opt.hlsearch = true -- highlight all matches for the last used search pattern
-- vim.opt.termguicolors = true	-- use GUI colors for the terminal
-- vim.opt.cursorcolumn = false	-- highlight the screen column of the cursor
vim.opt.cursorline = true -- highlight the screen line of the cursor
-- vim.opt.cursorlineopt = false	-- specifies which area 'cursorline' highlights
-- vim.opt.colorcolumn = false	-- columns to highlight
-- vim.opt.spell = true -- highlight spelling mistakes
vim.opt.spelllang = 'en_us' -- list of accepted languages
-- vim.opt.spellfile = false	-- file that "zg" adds good words to
-- vim.opt.spellcapcheck = false	-- pattern to locate the end of a sentence
-- vim.opt.spelloptions = false	-- flags to change how spell checking works
-- vim.opt.spellsuggest = false	-- methods used to suggest corrections
-- vim.opt.mkspellmem = false	-- amount of memory used by :mkspell before compressing
