-- vim.opt.showtabline = false	-- 0, 1 or 2; when to use a tab pages line
-- vim.opt.tabpagemax = false	-- maximum number of tab pages to open for -p and "tab all"
-- vim.opt.tabline = false	-- custom tab pages line
